<?php
declare(strict_types=1);

namespace HeleXa\Controllers\Admin;

use HeleXa\Core\Config;
use HeleXa\Core\Controller;
use HeleXa\Core\HttpException;
use HeleXa\Core\Paginator;
use HeleXa\Core\Request;
use HeleXa\Core\Response;
use HeleXa\Core\Str;
use HeleXa\Core\Validator;
use HeleXa\Models\AcademicRepository;
use HeleXa\Models\SessionRepository;
use HeleXa\Models\UserRepository;
use HeleXa\Services\ActivityLogger;
use HeleXa\Services\Auth;

final class StudentController extends Controller
{
    private const PER_PAGE = 20;

    private UserRepository $users;
    private AcademicRepository $academic;

    public function __construct()
    {
        $this->users    = new UserRepository();
        $this->academic = new AcademicRepository();
    }

    public function index(Request $request, array $params = []): Response
    {
        $filters = [
            'role'      => 'student',
            'search'    => $request->string('q'),
            'status'    => $this->allowedStatus($request->string('status')),
            'term_id'   => $request->int('term_id') ?: null,
            'group_id'  => $request->int('group_id') ?: null,
            'sort'      => $request->string('sort', 'created_at'),
            'direction' => $request->string('direction', 'desc'),
        ];

        $total     = $this->users->countFiltered($filters);
        $paginator = new Paginator($total, self::PER_PAGE, $request->int('page', 1), '/admin/students', [
            'q' => $filters['search'], 'status' => $filters['status'],
            'term_id' => $filters['term_id'], 'group_id' => $filters['group_id'],
        ]);

        return $this->page('layouts.app', 'admin.students.index', [
            'title'     => 'دانشجویان',
            'students'  => $this->users->paginate($filters, self::PER_PAGE, $paginator->offset()),
            'paginator' => $paginator,
            'filters'   => $filters,
            'terms'        => $this->academic->terms(),
            'groups'       => $this->academic->groups(),
            'universities' => $this->academic->universities(),
            'majors'       => $this->academic->majors(),
            'total'        => $total,
        ]);
    }

    public function create(Request $request, array $params = []): Response
    {
        return $this->page('layouts.app', 'admin.students.form', [
            'title'        => 'افزودن دانشجو',
            'student'      => null,
            'errors'       => [],
            'old'          => [],
            'selectedTerms'=> [],
            'terms'        => $this->academic->terms(),
            'groups'       => $this->academic->groups(),
            'universities' => $this->academic->universities(),
            'majors'       => $this->academic->majors(),
        ]);
    }

    public function store(Request $request, array $params = []): Response
    {
        $data      = $this->collect($request);
        $validator = $this->validate($data, null);

        // A temporary password is generated by the server; the admin never chooses it.
        $temporary = Str::temporaryPassword();

        if ($validator->fails() || $this->users->usernameExists($data['username'])) {
            $errors = $validator->errors();
            if ($this->users->usernameExists($data['username'])) {
                $errors['username'] = 'این نام کاربری قبلاً استفاده شده است.';
            }
            return $this->page('layouts.app', 'admin.students.form', [
                'title'         => 'افزودن دانشجو',
                'student'       => null,
                'errors'        => $errors,
                'old'           => $data,
                'selectedTerms' => $data['terms'],
                'terms'         => $this->academic->terms(),
                'groups'        => $this->academic->groups(),
                'universities'  => $this->academic->universities(),
                'majors'        => $this->academic->majors(),
            ], 422);
        }

        $roleId = (int) (new \HeleXa\Models\PermissionRepository())->roleBySlug('student')['id'];

        $id = $this->users->create([
            'uuid'                 => Str::uuid4(),
            'role_id'              => $roleId,
            'username'             => $data['username'],
            'mobile'               => $data['mobile'] ?: null,
            'email'                => $data['email'] ?: null,
            'password_hash'        => Auth::hashPassword($temporary),
            'must_change_password' => 1,
            'full_name'            => $data['full_name'],
            'major'                => $data['major'] ?: null,
            'term_id'              => $data['term_id'],
            'group_id'             => $data['group_id'],
            'status'               => $data['status'],
            'created_by'           => Auth::id(),
        ]);

        $this->academic->syncSemesters($id, $data['terms'], $data['major_id']);

        ActivityLogger::log('student.created', Auth::id(), 'user', $id, ['username' => $data['username']], 'notice', $request);

        // Shown once, immediately after creation.
        $_SESSION['_temp_password'] = ['username' => $data['username'], 'password' => $temporary];
        $this->flash('success', 'دانشجو ساخته شد. رمز موقت را همین حالا یادداشت کنید.');

        return $this->redirect('/admin/students');
    }

    public function edit(Request $request, array $params = []): Response
    {
        $student = $this->findStudent((string) ($params['uuid'] ?? ''));

        return $this->page('layouts.app', 'admin.students.form', [
            'title'         => 'ویرایش ' . $student['full_name'],
            'student'       => $student,
            'errors'        => [],
            'old'           => $student,
            'selectedTerms' => $this->academic->semestersOf((int) $student['id']),
            'terms'         => $this->academic->terms(),
            'groups'        => $this->academic->groups(),
            'universities'  => $this->academic->universities(),
            'majors'        => $this->academic->majors(),
        ]);
    }

    public function update(Request $request, array $params = []): Response
    {
        $student   = $this->findStudent((string) ($params['uuid'] ?? ''));
        $data      = $this->collect($request);
        $validator = $this->validate($data, (int) $student['id']);

        $errors = $validator->errors();
        if ($this->users->usernameExists($data['username'], (int) $student['id'])) {
            $errors['username'] = 'این نام کاربری قبلاً استفاده شده است.';
        }

        if ($errors !== []) {
            return $this->page('layouts.app', 'admin.students.form', [
                'title'         => 'ویرایش ' . $student['full_name'],
                'student'       => $student,
                'errors'        => $errors,
                'old'           => $data,
                'selectedTerms' => $data['terms'],
                'terms'         => $this->academic->terms(),
                'groups'        => $this->academic->groups(),
                'universities'  => $this->academic->universities(),
                'majors'        => $this->academic->majors(),
            ], 422);
        }

        $this->users->update((int) $student['id'], $data);
        $this->academic->syncSemesters((int) $student['id'], $data['terms'], $data['major_id']);

        // Losing "active" status must take effect immediately, not at next login.
        if ($data['status'] !== 'active') {
            (new SessionRepository())->terminateAllForUser((int) $student['id'], 'admin_force', Auth::id());
        }

        ActivityLogger::log('student.updated', Auth::id(), 'user', (int) $student['id'], [], 'notice', $request);
        $this->flash('success', 'اطلاعات دانشجو به‌روزرسانی شد.');

        return $this->redirect('/admin/students');
    }

    public function setStatus(Request $request, array $params = []): Response
    {
        $student = $this->findStudent((string) ($params['uuid'] ?? ''));
        $status  = $this->allowedStatus($request->string('status'));

        if ($status === null) {
            throw HttpException::forbidden('وضعیت نامعتبر است.');
        }

        $this->users->setStatus((int) $student['id'], $status);
        if ($status !== 'active') {
            (new SessionRepository())->terminateAllForUser((int) $student['id'], 'admin_force', Auth::id());
            Auth::revokeRememberTokens((int) $student['id'], 'admin');
        }

        ActivityLogger::log('student.status_changed', Auth::id(), 'user', (int) $student['id'],
            ['status' => $status], 'notice', $request);
        $this->flash('success', 'وضعیت دانشجو تغییر کرد.');

        return $this->redirect('/admin/students');
    }

    public function resetPassword(Request $request, array $params = []): Response
    {
        $student   = $this->findStudent((string) ($params['uuid'] ?? ''));
        $temporary = Str::temporaryPassword();

        $this->users->markMustChangePassword((int) $student['id'], Auth::hashPassword($temporary));
        (new SessionRepository())->terminateAllForUser((int) $student['id'], 'password_change', Auth::id());
        Auth::revokeRememberTokens((int) $student['id'], 'password_change');

        ActivityLogger::log('student.password_reset', Auth::id(), 'user', (int) $student['id'], [], 'warning', $request);

        $_SESSION['_temp_password'] = ['username' => $student['username'], 'password' => $temporary];
        $this->flash('success', 'رمز موقت ساخته شد و همه نشست‌های کاربر بسته شد.');

        return $this->redirect('/admin/students');
    }

    public function unlock(Request $request, array $params = []): Response
    {
        $student = $this->findStudent((string) ($params['uuid'] ?? ''));
        $this->users->unlock((int) $student['id']);

        ActivityLogger::log('student.unlocked', Auth::id(), 'user', (int) $student['id'], [], 'notice', $request);
        $this->flash('success', 'قفل ورود برداشته شد.');

        return $this->redirect('/admin/students');
    }

    public function destroy(Request $request, array $params = []): Response
    {
        $student = $this->findStudent((string) ($params['uuid'] ?? ''));

        (new SessionRepository())->terminateAllForUser((int) $student['id'], 'admin_force', Auth::id());
        Auth::revokeRememberTokens((int) $student['id'], 'admin');
        $this->users->softDelete((int) $student['id']);

        ActivityLogger::log('student.deleted', Auth::id(), 'user', (int) $student['id'],
            ['username' => $student['username']], 'warning', $request);
        $this->flash('success', 'دانشجو حذف شد. سوابق فعالیت او برای گزارش‌ها باقی می‌ماند.');

        return $this->redirect('/admin/students');
    }

    /* ------------------------------------------------------------ helpers */

    private function findStudent(string $uuid): array
    {
        $student = $this->users->findByUuid($uuid);
        if ($student === null || $student['role_slug'] !== 'student') {
            throw HttpException::notFound('دانشجو یافت نشد.');
        }
        return $student;
    }

    private function allowedStatus(string $status): ?string
    {
        return in_array($status, ['active', 'inactive', 'suspended'], true) ? $status : null;
    }

    /**
     * Validates the whole academic chain, not each field on its own.
     *
     * University -> major -> term -> group is a hierarchy, so a value that
     * does not belong to the level above it is dropped rather than stored.
     * Otherwise a stale <option> left in a cached page could quietly attach a
     * student to another university's group and break every schedule lookup.
     */
    private function collect(Request $request): array
    {
        $universityId = $request->int('university_id') ?: null;
        $majorId      = $request->int('major_id') ?: null;
        $groupId      = $request->int('group_id') ?: null;

        if ($universityId !== null && $this->academic->findUniversity($universityId) === null) {
            $universityId = null;
        }
        if ($majorId !== null && ($universityId === null
            || !$this->academic->majorBelongsToUniversity($majorId, $universityId))) {
            $majorId = null;
        }

        // Terms: multi-select, each checked against the chosen major.
        $requested = $request->input('terms', []);
        $termIds   = [];
        if (is_array($requested)) {
            foreach ($requested as $value) {
                $id = (int) $value;
                if ($id > 0 && $this->academic->termBelongsToMajor($id, $majorId)) {
                    $termIds[] = $id;
                }
            }
        }
        $termIds   = array_values(array_unique($termIds));
        $primary   = $termIds[0] ?? null;

        // The group must sit under one of the terms the student is actually in.
        if ($groupId !== null) {
            $belongs = false;
            foreach ($termIds as $termId) {
                if ($this->academic->groupBelongsToTerm($groupId, $termId)) {
                    $belongs = true;
                    break;
                }
            }
            if (!$belongs) {
                $groupId = null;
            }
        }

        $gender = $request->string('gender');
        if (!in_array($gender, ['male', 'female'], true)) {
            $gender = null;
        }

        return [
            'full_name'     => $request->string('full_name'),
            'username'      => $request->string('username'),
            'mobile'        => \HeleXa\Services\Jalali::toLatinDigits($request->string('mobile')),
            'email'         => $request->string('email'),
            'gender'        => $gender,
            'major'         => $request->string('major'),
            'university_id' => $universityId,
            'major_id'      => $majorId,
            'term_id'       => $primary,
            'group_id'      => $groupId,
            'terms'         => $termIds,
            'status'        => $this->allowedStatus($request->string('status', 'active')) ?? 'active',
        ];
    }

    private function validate(array $data, ?int $exceptId): Validator
    {
        return (new Validator($data))
            ->required('full_name', 'نام کامل')
            ->length('full_name', 'نام کامل', 3, 191)
            ->required('username', 'نام کاربری')
            ->username('username', 'نام کاربری')
            ->mobile('mobile', 'شماره موبایل');
    }
}
