<?php
/**
 * HeleXa Med — main configuration.
 * This file lives OUTSIDE public_html and is generated by install.php.
 * Never commit real credentials to version control.
 */
return [
    'app' => [
        'name'        => 'HeleXa Med',
        'url'         => 'https://example.com',
        'timezone'    => 'Asia/Tehran',
        'environment' => 'production', // production | development
        'debug'       => false,
    ],

    'database' => [
        'host'     => 'localhost',
        'port'     => 3306,
        'name'     => '',
        'user'     => '',
        'password' => '',
        'charset'  => 'utf8mb4',
    ],

    'security' => [
        // 64 hex chars, generated at install time. Rotating it invalidates
        // every device fingerprint and forces a fresh login everywhere.
        'app_key'        => '',
        'force_https'    => true,
        'trust_proxy'    => false, // enable only behind a proxy you control
        'session_name'   => 'HLX_SID',
        'cookie_samesite'=> 'Lax',
        'argon_memory'   => 65536,
        'argon_time'     => 4,
        'argon_threads'  => 1,
    ],
];
