package ir.helexapanel.app

/** Generated by tools/typecheck-ui.sh from res/values/strings.xml. */
object R {
    object string {
        const val action_cancel = 1
        const val action_sign_in = 2
        const val action_sign_out = 3
        const val app_name = 4
        const val cd_avatar = 5
        const val cd_back = 6
        const val field_identifier = 7
        const val field_password = 8
        const val nav_courses = 9
        const val nav_home = 10
        const val nav_notifications = 11
        const val nav_profile = 12
        const val nav_schedule = 13
        const val sign_in_help = 14
        const val sign_in_subtitle = 15
        const val sign_in_title = 16
        const val sign_out_confirm_body = 17
        const val sign_out_confirm_title = 18
        const val state_empty_courses = 19
        const val state_empty_exams = 20
        const val state_empty_notifications = 21
        const val state_empty_schedule = 22
        const val state_loading = 23
        const val state_offline = 24
        const val state_retry = 25
    }
}
